/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSlugRouteImport } from './routes/section.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as ApiPublicConciergeChartRouteImport } from './routes/api/public/concierge-chart'
import { Route as ApiPublicConciergeRouteImport } from './routes/api/public/concierge'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicConciergeChartRoute = ApiPublicConciergeChartRouteImport.update({
  id: '/api/public/concierge-chart',
  path: '/api/public/concierge-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConciergeRoute = ApiPublicConciergeRouteImport.update({
  id: '/api/public/concierge',
  path: '/api/public/concierge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/terminal': typeof TerminalRoute
  '/admin/posts': typeof AdminPostsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/concierge-chart': typeof ApiPublicConciergeChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/terminal': typeof TerminalRoute
  '/admin/posts': typeof AdminPostsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/concierge-chart': typeof ApiPublicConciergeChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/terminal': typeof TerminalRoute
  '/admin/posts': typeof AdminPostsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/concierge-chart': typeof ApiPublicConciergeChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/terminal'
    | '/admin/posts'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/concierge'
    | '/api/public/concierge-chart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/terminal'
    | '/admin/posts'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/concierge'
    | '/api/public/concierge-chart'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/terminal'
    | '/admin/posts'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/concierge'
    | '/api/public/concierge-chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  TerminalRoute: typeof TerminalRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  SectionSlugRoute: typeof SectionSlugRoute
  ApiPublicConciergeRoute: typeof ApiPublicConciergeRoute
  ApiPublicConciergeChartRoute: typeof ApiPublicConciergeChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$slug': {
      id: '/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/concierge-chart': {
      id: '/api/public/concierge-chart'
      path: '/api/public/concierge-chart'
      fullPath: '/api/public/concierge-chart'
      preLoaderRoute: typeof ApiPublicConciergeChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/concierge': {
      id: '/api/public/concierge'
      path: '/api/public/concierge'
      fullPath: '/api/public/concierge'
      preLoaderRoute: typeof ApiPublicConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  TerminalRoute: TerminalRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  SectionSlugRoute: SectionSlugRoute,
  ApiPublicConciergeRoute: ApiPublicConciergeRoute,
  ApiPublicConciergeChartRoute: ApiPublicConciergeChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
